apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: instapay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: instapay-user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_APPLICATION_NAME
          value: user-service
        - name: SERVER_PORT
          value: "8081"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_INSTANCE_ID
          value: "${HOSTNAME}"
        - name: EUREKA_INSTANCE_APPNAME
          value: user-service
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-service:8761/eureka/
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/instapay_user
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://zipkin:9411/api/v2/spans
        - name: MANAGEMENT_ZIPKIN_TRACING_SERVICE_NAME
          value: user-service
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        - name: MANAGEMENT_TRACING_BAGGAGE_REMOTE_FIELDS
          value: "*"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus,httptrace,loggers"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: MANAGEMENT_TRACING_ENABLED
          value: "true"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
          value: "INFO"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD
          value: "INFO"
        - name: LOGGING_LEVEL_COM_KARIM
          value: "DEBUG"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: instapay
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30006  
  type: NodePort